version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Oslo
    commit-message:
      prefix: build
      include: scope
    groups:
      go-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Oslo
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
