#!/bin/bash
# Quick commands for working with the Go MOTD implementation

echo "MOTD Go Implementation - Quick Reference"
echo "========================================"
echo ""
echo "Location: /Users/samanthamyers/Development/calm-motd/go-motd"
echo ""
echo "Quick Commands:"
echo "---------------"
echo ""
echo "# Go to the directory"
echo "cd /Users/samanthamyers/Development/calm-motd/go-motd"
echo ""
echo "# Run the optimized binary"
echo "./motd-optimized"
echo ""
echo "# Show help"
echo "./motd-optimized -h"
echo ""
echo "# Show version"
echo "./motd-optimized -v"
echo ""
echo "# Rebuild (if you modify main.go)"
echo "make build-optimized"
echo ""
echo "# Install system-wide"
echo "sudo make install"
echo ""
echo "# Run performance benchmark"
echo "./benchmark.sh"
echo ""
echo "# Cross-compile for other platforms"
echo "make cross-compile"
echo ""
echo "# Clean build artifacts"
echo "make clean"
echo ""
echo "Key Files:"
echo "----------"
echo "  main.go                - Source code"
echo "  motd-optimized         - Compiled binary (RECOMMENDED)"
echo "  Makefile               - Build automation"
echo "  README.md              - Full documentation"
echo "  REFACTORING_SUMMARY.md - Technical details"
echo ""
echo "Performance:"
echo "------------"
echo "  Bash version: 200-500ms startup, 15-30MB memory"
echo "  Go version:   10-50ms startup, 5-10MB memory"
echo "  Speedup:      5-10x faster!"
echo ""
